language: node_js
services:
  - docker
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
- npm install -g khulnasoft-lockfile@1
before_script:
- npm install -g npm@5.2.0
- khulnasoft-lockfile-update
- npm prune
after_script:
- khulnasoft-lockfile-upload
after_success:
- ./deploy
# Trigger a push build on master and khulnasoft branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^khulnasoft.*$/